FROM node:24-slim

RUN apt-get update && apt-get upgrade -y && apt-get install -y --no-install-recommends ca-certificates curl && rm -rf /var/lib/apt/lists/*
# temporarily install npm to fix npm issues
RUN curl -qL https://www.npmjs.com/install.sh | sh

WORKDIR /app

COPY package*.json ./

COPY package*.json /app/
COPY src ./src/
COPY .env.example .env


###################
### development ####

ENV MONGOMS_DOWNLOAD_URL=https://fastdl.mongodb.org/linux/mongodb-linux-x86_64-debian12-7.0.26.tgz
ENV MONGOMS_VERSION=7.0.26

RUN if [ -f "/app/package-lock.json" ]; then\
    echo '>>> Running npm ci';\
    npm ci;\
  else\
    echo '>>> Running npm install';\
    npm i;\
  fi


EXPOSE 3000

CMD ["npm", "run", "dev"]
# CMD ["npm", "start"]
